general: null
steps:
    mtaBuild:
        buildTarget: CF
        mtaJarLocation: /opt/sap/mta/lib/mta.jar
        dockerImage: ppiper/mta-archive-builder
    cloudFoundryDeploy:
        deployTool: mtaDeployPlugin
        deployType: standard
        cloudFoundry:
            org: S0004462440trial_trial
            space: dev
            credentialsId: CF_CREDENTIALSID
