steps:
    mtaBuild:
        buildTarget: CF
        mtaJarLocation: '/opt/sap/mta/lib/mta_archive_builder-1.1.19.jar'
        dockerImage: 'sonatype/nexus3'
    cloudFoundryDeploy:
        deployTool: mtaDeployPlugin
        deployType: standard
        cloudFoundry:
            org: S0004462440trial_trial
            space: dev
            credentialsId: CF_CREDENTIALSID
