steps:
    mtaBuild:
        buildTarget: CF
        mtaJarLocation: '/sapmnt/jenkins/workspace/CF\ Pipeline/mta.jar'
        dockerImage: 'sonatype/nexus3'
    cloudFoundryDeploy:
        deployTool: mtaDeployPlugin
        deployType: standard
        cloudFoundry:
            org: S0004462440trial_trial
            space: dev
            credentialsId: CF_CREDENTIALSID
