steps:
    mtaBuild:
        buildTarget: CF
        mtaJarLocation: '/var/jenkins_home/mta.jar'
        dockerImage: '/usr/bin/docker'
    cloudFoundryDeploy:
        deployTool: mtaDeployPlugin
        deployType: standard
        cloudFoundry:
            org: S0004462440trial_trial
            space: dev
            credentialsId: CF_CREDENTIALSID
