steps:
    mtaBuild:
        buildTarget: CF
        mtaJarLocation: '/sapmnt/mta_builder/mta_archive_builder-1.1.20.jar'
        dockerImage: 'sonatype/nexus3'
    cloudFoundryDeploy:
        deployTool: mtaDeployPlugin
        deployType: standard
        cloudFoundry:
            org: S0004462440trial_trial
            space: dev
            credentialsId: CF_CREDENTIALSID
